# gmaps_scraper_project/config.py

# -*- coding: utf-8 -*-

# --- Configuration Variables ---

# List of major cities in Australia
REGIONS_AND_CITIES = {   'Australian Capital Territory': ['Canberra'],
    'New South Wales': [   'Aberdare',
                           'Albury',
                           'Alstonville',
                           'Armidale',
                           'Ballina',
                           'Bangalow',
                           'Banora Point',
                           'Batehaven',
                           'Bathurst',
                           'Bay View',
                           'Bellingen',
                           'Blaxland',
                           'Blayney',
                           'Bogangar',
                           'Bomaderry',
                           'Bonny Hills',
                           'Bourke',
                           'Bowral',
                           'Brunswick Heads',
                           'Camden Haven',
                           'Campbelltown',
                           'Canowindra',
                           'Casino',
                           'Central Coast',
                           'Cessnock',
                           'Cobar',
                           'Condobolin',
                           'Cootamundra',
                           'Corowa',
                           'Cowra',
                           'Culburra',
                           'Deniliquin',
                           'Denman',
                           'Eden',
                           'Emu Plains',
                           'Flemington',
                           'Forster',
                           'Gerringong',
                           'Gilgandra',
                           'Glen Innes',
                           'Glenbrook',
                           'Goonellabah',
                           'Grafton',
                           'Greenwell Point',
                           'Grenfell',
                           'Griffith',
                           'Hazelbrook',
                           'Heddon Greta',
                           'Helensburgh',
                           'Hill Top',
                           'Howlong',
                           'Inverell',
                           'Jindabyne',
                           'Katoomba',
                           'Kiama Downs',
                           'Kingscliff',
                           'Kurri Kurri',
                           'Lake Cathie',
                           'Lawson',
                           'Leeton',
                           'Lennox Head',
                           'Lismore',
                           'Lithgow',
                           'Manilla',
                           'Merimbula',
                           'Merrimac',
                           'Mittagong',
                           'Moama',
                           'Mollymook',
                           'Moree',
                           'Moss Vale',
                           'Mudgee',
                           'Mullumbimby',
                           'Mulwala',
                           'Murwillumbah',
                           'Muswellbrook',
                           'Nambucca Heads',
                           'Narooma',
                           'Narrabri',
                           'Narrandera',
                           'Newcastle',
                           'Nowra',
                           'Oakdale',
                           'Old Bar',
                           'Parkes',
                           'Penrith',
                           'Picton',
                           'Port Macquarie',
                           'Quakers Hill',
                           'Quirindi',
                           'Richmond',
                           'Rutherford',
                           'Saint Georges Basin',
                           'Salamander Bay',
                           'Sanctuary Point',
                           'Sandy Beach',
                           'Sawtell',
                           'Scone',
                           'Shoalhaven Heads',
                           'Silverdale',
                           'Springwood',
                           'Suffolk Park',
                           'Surfside',
                           'Sydney',
                           'Tahmoor',
                           'Taree',
                           'Tathra',
                           'Tea Gardens',
                           'Temora',
                           'Terranora',
                           'The Entrance',
                           'The Oaks',
                           'Thirlmere',
                           'Tumut',
                           'Tuncurry',
                           'Tura Beach',
                           'Tweed Heads',
                           'Urunga',
                           'Valley Heights',
                           'Vincentia',
                           'Wagga Wagga',
                           'Walgett',
                           'Wallerawang',
                           'Wauchope',
                           'Wellington',
                           'West Wyalong',
                           'Weston',
                           'Wilton',
                           'Windsor',
                           'Wingham',
                           'Wollongong',
                           'Woolgoolga',
                           'Worragee',
                           'Wyong',
                           'Yamba',
                           'Yass',
                           'Young'],
    'Northern Territory': ['Darwin', 'Palmerston'],
    'Queensland': [   'Andergrove',
                      'Bargara',
                      'Beachmere',
                      'Beenleigh',
                      'Bongaree',
                      'Brisbane',
                      'Bucasia',
                      'Buderim',
                      'Burpengary',
                      'Cairns',
                      'Caloundra',
                      'Cannonvale',
                      'Charters Towers',
                      'Corinda',
                      'Deeragun',
                      'Freshwater',
                      'Gladstone',
                      'Glenella',
                      'Gold Coast',
                      'Hervey Bay',
                      'Innisfail',
                      'Ipswich',
                      'Kawana Waters',
                      'Kingaroy',
                      'Mackay',
                      'Mareeba',
                      'Maroochydore',
                      'Nambour',
                      'North Mackay',
                      'Ormeau',
                      'Palmwoods',
                      'Peregian Beach',
                      'Point Vernon',
                      'Proserpine',
                      'Rasmussen',
                      'Scarness',
                      'Southport',
                      'Thursday Island',
                      'Toowoomba',
                      'Townsville',
                      'Urraween',
                      'Waterford',
                      'Yaroomba'],
    'South Australia': [   'Adelaide',
                           'Aldgate',
                           'Barmera',
                           'Berri',
                           'Encounter Bay',
                           'Freeling',
                           'Goolwa',
                           'Hahndorf',
                           'Kapunda',
                           'Lobethal',
                           'Loxton',
                           'Lyndoch',
                           'McLaren Vale',
                           'Millicent',
                           'Mount Barker',
                           'Mount Gambier',
                           'Murray Bridge',
                           'Nairne',
                           'Nuriootpa',
                           'Port Augusta',
                           'Renmark',
                           'Roxby Downs',
                           'Stirling',
                           'Strathalbyn',
                           'Tanunda',
                           'Victor Harbor',
                           'Waikerie',
                           'Whyalla',
                           'Williamstown',
                           'Willunga',
                           'Woodside'],
    'Tasmania': [   'Burnie',
                    'Deloraine',
                    'Dodges Ferry',
                    'Evandale',
                    'George Town',
                    'Hadspen',
                    'Hobart',
                    'Kingston',
                    'Latrobe',
                    'Launceston',
                    'Legana',
                    'Longford',
                    'Margate',
                    'New Norfolk',
                    'Penguin',
                    'Perth',
                    'Queenstown',
                    'Seven Mile Beach',
                    'Smithton',
                    'Somerset',
                    'Ulverstone',
                    'Westbury',
                    'Wynyard'],
    'Victoria': [   'Ballarat',
                    'Barwon Heads',
                    'Baxter',
                    'Beaconsfield Upper',
                    'Bendigo',
                    'Broadford',
                    'Buninyong',
                    'Camperdown',
                    'Castlemaine',
                    'Churchill',
                    'Clifton Springs',
                    'Cobden',
                    'Cockatoo',
                    'Colac',
                    'Cranbourne',
                    'Curlewis',
                    'Dandenong',
                    'Dromana',
                    'Drysdale',
                    'Euroa',
                    'Frankston',
                    'Geelong',
                    'Horsham',
                    'Inverloch',
                    'Kerang',
                    'Koo-Wee-Rup',
                    'Korumburra',
                    'Kyabram',
                    'Lakes Entrance',
                    'Lara',
                    'Launching Place',
                    'Leongatha',
                    'Leopold',
                    'Maddingley',
                    'Maffra',
                    'Mansfield',
                    'Maryborough',
                    'McCrae',
                    'Melbourne',
                    'Mooroopna',
                    'Morwell',
                    'Mount Eliza',
                    'Mount Evelyn',
                    'Narre Warren North',
                    'Nathalia',
                    'North Wonthaggi',
                    'Numurkah',
                    'Orbost',
                    'Pakenham',
                    'Paynesville',
                    'Pearcedale',
                    'Port Fairy',
                    'Red Cliffs',
                    'Rutherglen',
                    'Rye',
                    'Saint Arnaud',
                    'San Remo',
                    'Seymour',
                    'Stawell',
                    'Sunbury',
                    'Swan Hill',
                    'Tatura',
                    'Trafalgar',
                    'Traralgon',
                    'Wahgunyah',
                    'Wallan',
                    'Warrnambool',
                    'Wattleglen',
                    'Whittlesea',
                    'Woori Yallock',
                    'Yallourn North',
                    'Yarragon',
                    'Yarram'],
    'Western Australia': [   'Australind',
                             'Boulder',
                             'Drummond Cove',
                             'Esperance',
                             'Fremantle',
                             'Mandurah',
                             'Perth']}

USER_AGENT_LIST = [
    # Existing
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183',
]


# Default output filename
DEFAULT_OUTPUT_FILENAME = "gmaps_self_storage_data.xlsx"

# Scraping limits (optional)
MAX_RESULTS_TO_COLLECT_PER_CITY = 150
MAX_RESULTS_TO_PROCESS_PER_CITY = 150
MAX_SCROLL_ATTEMPTS = 15

# Debug log filename
DEBUG_LOG_FILENAME = 'gmaps_scraper_debug.log'

# Default theme settings
THEME_SETTINGS_FILE = "theme_setting.txt"
